version: '2'

services:
  otrs-app:
    image: otrs:latest
    container_name: otrs-app
    links:
      - otrs-db
    volumes:
      - ./conf:/opt/otrs/Kernel
      - ./logs/:/var/log/nginx/logs
    environment:
      - VIRTUAL_HOST=otrs.examplre.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=otrs.example.com
      - LETSENCRYPT_EMAIL=admin@example.com

      - ZABBIX_HOSTNAME=otrs-app
 
      - DB_HOST=otrs-db
      - DB_NAME=otrs
      - DB_USER=otrs
      - DB_PASS=otrs

      - ORGANIZATION=Docker OTRS
      - ROOT_PASS=otrs
      - ADMIN_EMAIL=sysadmin@email.com

    networks:
      - proxy-tier
    restart: always

  otrs-db:
    image: tiredofit/mariadb
    container_name: otrs-db
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - /var/local/db/otrs-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=otrs
      - MYSQL_DATABASE=otrs
      - MYSQL_USER=otrs
      - MYSQL_PASSWORD=otrs

      - ZABBIX_HOSTNAME=otrs-db
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

